// generated by build-web.mjs — app shell cache (no API data is cached here)
const CACHE = "gundem-b77d87d082";
const SHELL = ["./","runtime.js?v=47f82a6636","config.js?v=e6c9d39d60","capacitor.js?v=8a3d7cfb86","icon-180.png?v=01d3b00363","icon-192.png?v=3818bcea33","manifest.webmanifest?v=07c5fe4123"];
self.addEventListener("install", (e) => { e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting())); });
self.addEventListener("activate", (e) => { e.waitUntil(caches.keys().then((ks) => Promise.all(ks.filter((k) => k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim())); });
self.addEventListener("fetch", (e) => {
  const u = new URL(e.request.url);
  if (e.request.method !== "GET" || u.origin !== location.origin) return;
  if (/^\/(api|auth|webhooks|health)\b/.test(u.pathname)) return;           // live data and login: always network
  if (e.request.mode === "navigate" && (u.pathname === "/" || u.pathname === "/index.html")) {
    // stale-while-revalidate: show the cached shell now, refresh it in the background for next time
    e.respondWith(caches.open(CACHE).then(async (c) => {
      const hit = await c.match("./");
      const net = fetch(e.request).then((r) => { if (r.ok) c.put("./", r.clone()); return r; });
      return hit || net;
    }));
    return;
  }
  if (u.searchParams.has("v")) e.respondWith(caches.open(CACHE).then(async (c) => (await c.match(e.request)) || fetch(e.request).then((r) => { if (r.ok) c.put(e.request, r.clone()); return r; })));   // versioned = immutable
});
